GET http://localhost:3000/api/v1/cards


###
GET http://localhost:3000/api/v1/cards/06c7b0cb-2a0d-4bfa-844f-0b438ee08937


###
POST http://localhost:3000/api/v1/cards
Content-Type: application/json

{
  "uuid": "78438394893443",
  "balance": 0
}


###
PUT http://localhost:3000/api/v1/cards/06c7b0cb-2a0d-4bfa-844f-0b438ee08937
Content-Type: application/json

{
  "balance": 5000
}
